### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by alessiovaralta**
Tab map complete

### CODE REVIEW

**Comment by ilvalle** [comment]
Well done.
However, before merging it, I ask to remove some odd files.
all files ending with .bak and ~,
all files in  static/font-awesome/less
all files called Thumbs.db, .DS_Store
in general all files not required for the development of the app.

2015-06-05 11:42 GMT+02:00 alessiovaralta notifications@github.com:

**Comment by alessiovaralta** [comment]
I have deleted the back file,static/font-awesome/less and the Thumbs.db

**Comment by ilvalle** [comment]
ok, however I still see files ending with ~, files called .DS_Store. 
In addition, I think you can remove all .scss files too

**Comment by alessiovaralta** [comment]
I have deleted  ~, files called .DS_Store,.scss and now i work on the last features

**Comment by ilvalle** [comment]
I ask if you can rebase the pull request into a single commit with a better message rather than first/second/third etc...

**Pull request closed without merging**
